-- The schema of a database migrated from empty, at user_version 5.
-- Generated by TestSchemaLatestMatchesAFreshMigration; rewrite it with
-- go test ./internal/vault -run TestSchemaLatest -update

CREATE TABLE profiles (
    id                  TEXT    PRIMARY KEY,     -- UUID
    token               TEXT    NOT NULL UNIQUE, -- URL slug, e.g. /u/{token}/...
    nuvio_user_id       TEXT    NOT NULL,         -- Nuvio auth.users.id (the account)
    nuvio_profile_index INTEGER NOT NULL,         -- Nuvio profile slot, 1..6
    nuvio_profile_uuid  TEXT    NOT NULL,         -- Nuvio profile row's own id; detects slot reuse

    UNIQUE (nuvio_user_id, nuvio_profile_index),
    CHECK  (nuvio_profile_index BETWEEN 1 AND 6)
);

CREATE TABLE folders (
    id                TEXT    PRIMARY KEY,
    collection_id     TEXT    NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    title             TEXT    NOT NULL,
    sort_order        INTEGER NOT NULL,
    tile_shape        TEXT    NOT NULL DEFAULT 'LANDSCAPE',
    hide_title        INTEGER NOT NULL DEFAULT 0,
    cover_emoji       TEXT    NOT NULL DEFAULT '',
    cover_image_url   TEXT    NOT NULL DEFAULT '',
    focus_gif_url     TEXT    NOT NULL DEFAULT '',
    focus_gif_enabled INTEGER NOT NULL DEFAULT 1,
    hero_video_url    TEXT    NOT NULL DEFAULT '',
    hero_backdrop_url TEXT    NOT NULL DEFAULT '',
    title_logo_url    TEXT    NOT NULL DEFAULT ''
, sub_key TEXT);

CREATE INDEX folders_by_collection ON folders (collection_id, sort_order);

CREATE TABLE folder_catalogs (
    folder_id  TEXT    NOT NULL REFERENCES folders(id) ON DELETE CASCADE,
    catalog_id TEXT    NOT NULL REFERENCES catalogs(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    genre      TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (folder_id, catalog_id, genre)
);

CREATE INDEX folder_catalogs_by_order ON folder_catalogs (folder_id, sort_order);

CREATE TABLE recipes (
    hash       TEXT PRIMARY KEY, -- sha256 hex of uno-recipe/1, type, provider and params
    type       TEXT NOT NULL,    -- Stremio's word: movie | series
    provider   TEXT NOT NULL,    -- tmdb, for now
    params     TEXT NOT NULL,    -- canonical JSON: known keys, no zero values, keys sorted
    created_at TEXT NOT NULL     -- RFC3339 UTC
);

CREATE TABLE "collections" (
    id                 TEXT    PRIMARY KEY,
    title              TEXT    NOT NULL,
    owner_id           TEXT    NOT NULL REFERENCES profiles(id),
    pin_to_top         INTEGER NOT NULL DEFAULT 0,
    view_mode          TEXT    NOT NULL DEFAULT 'TABBED_GRID',
    show_all_tab       INTEGER NOT NULL DEFAULT 0,
    backdrop_image_url TEXT    NOT NULL DEFAULT '',
    focus_glow_enabled INTEGER NOT NULL DEFAULT 1,
    home_sort_order    INTEGER,                    -- NULL = not on the TV
    created_at         TEXT    NOT NULL,           -- RFC3339 UTC
    updated_at         TEXT    NOT NULL            -- RFC3339 UTC
, pushed_hash TEXT);

CREATE INDEX collections_by_owner ON collections (owner_id);

CREATE TABLE "catalogs" (
    id              TEXT    PRIMARY KEY,         -- UUID, permanent once selected
    name            TEXT    NOT NULL,
    recipe_hash     TEXT    NOT NULL REFERENCES recipes(hash),
    owner_id        TEXT    NOT NULL REFERENCES profiles(id),
    collection_id   TEXT    REFERENCES collections(id) ON DELETE CASCADE, -- NULL = listed
    home_sort_order INTEGER,                     -- NULL = not on the TV
    show_in_home    INTEGER NOT NULL DEFAULT 1,  -- whether the home row appears when on the TV
    sub_key         TEXT,                        -- in a subscribed collection: its key in the snapshot
    created_at      TEXT    NOT NULL,            -- RFC3339 UTC
    updated_at      TEXT    NOT NULL,            -- RFC3339 UTC
    CHECK (collection_id IS NULL OR home_sort_order IS NULL)
);

CREATE INDEX catalogs_by_owner ON catalogs (owner_id);

CREATE INDEX catalogs_by_collection ON catalogs (collection_id);

CREATE INDEX catalogs_by_recipe ON catalogs (recipe_hash);

CREATE TRIGGER recipes_drop_unused_on_delete AFTER DELETE ON catalogs
WHEN NOT EXISTS (SELECT 1 FROM catalogs WHERE recipe_hash = OLD.recipe_hash)
BEGIN
    DELETE FROM recipes WHERE hash = OLD.recipe_hash;
END;

CREATE TRIGGER recipes_drop_unused_on_repoint AFTER UPDATE OF recipe_hash ON catalogs
WHEN OLD.recipe_hash IS NOT NEW.recipe_hash
 AND NOT EXISTS (SELECT 1 FROM catalogs WHERE recipe_hash = OLD.recipe_hash)
BEGIN
    DELETE FROM recipes WHERE hash = OLD.recipe_hash;
END;

CREATE TABLE publications (
    id               TEXT    PRIMARY KEY,         -- UUID, kept across republishes
    owner_id         TEXT    NOT NULL REFERENCES profiles(id),
    kind             TEXT    NOT NULL CHECK (kind IN ('catalog', 'collection')),
    catalog_id       TEXT    REFERENCES catalogs(id) ON DELETE SET NULL,    -- the source; NULL once deleted
    collection_id    TEXT    REFERENCES collections(id) ON DELETE SET NULL, -- the source; NULL once deleted
    title            TEXT    NOT NULL,
    snapshot         TEXT    NOT NULL,            -- JSON, format uno-publication
    content_hash     TEXT    NOT NULL,            -- sha256 hex of snapshot
    catalog_count    INTEGER NOT NULL,
    folder_count     INTEGER NOT NULL,
    subscriber_count INTEGER NOT NULL DEFAULT 0,
    status           TEXT    NOT NULL CHECK (status IN ('live', 'withdrawn')),
    published_at     TEXT    NOT NULL,            -- RFC3339 UTC, when first published
    updated_at       TEXT    NOT NULL,            -- RFC3339 UTC
    CHECK (kind = 'catalog' OR catalog_id IS NULL),
    CHECK (kind = 'collection' OR collection_id IS NULL)
);

CREATE UNIQUE INDEX publications_by_catalog ON publications (catalog_id) WHERE catalog_id IS NOT NULL;

CREATE UNIQUE INDEX publications_by_collection ON publications (collection_id) WHERE collection_id IS NOT NULL;

CREATE TABLE subscriptions (
    id             TEXT PRIMARY KEY,
    owner_id       TEXT NOT NULL REFERENCES profiles(id),
    publication_id TEXT NOT NULL REFERENCES publications(id),
    catalog_id     TEXT REFERENCES catalogs(id) ON DELETE CASCADE,    -- the copy, for a catalog
    collection_id  TEXT REFERENCES collections(id) ON DELETE CASCADE, -- the copy, for a collection
    taken_hash     TEXT NOT NULL,                -- the content hash the copy was last written from
    created_at     TEXT NOT NULL,                -- RFC3339 UTC
    UNIQUE (owner_id, publication_id),
    CHECK ((catalog_id IS NULL) <> (collection_id IS NULL))
);

CREATE UNIQUE INDEX subscriptions_by_catalog ON subscriptions (catalog_id) WHERE catalog_id IS NOT NULL;

CREATE UNIQUE INDEX subscriptions_by_collection ON subscriptions (collection_id) WHERE collection_id IS NOT NULL;

CREATE TRIGGER publications_withdraw_on_source_delete AFTER UPDATE OF catalog_id, collection_id ON publications
WHEN NEW.catalog_id IS NULL AND NEW.collection_id IS NULL AND NEW.status = 'live'
BEGIN
    UPDATE publications SET status = 'withdrawn', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
    WHERE id = NEW.id;
END;

CREATE TRIGGER publications_withdraw_on_scope AFTER UPDATE OF collection_id ON catalogs
WHEN NEW.collection_id IS NOT NULL
BEGIN
    UPDATE publications SET status = 'withdrawn', updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
    WHERE (catalog_id, status) = (NEW.id, 'live');
END;

CREATE TRIGGER subscriptions_count_on_insert AFTER INSERT ON subscriptions
BEGIN
    UPDATE publications SET subscriber_count = subscriber_count + 1 WHERE id = NEW.publication_id;
END;

CREATE TRIGGER subscriptions_count_on_delete AFTER DELETE ON subscriptions
BEGIN
    UPDATE publications SET subscriber_count = subscriber_count - 1 WHERE id = OLD.publication_id;
END;

CREATE TABLE accounts (
    nuvio_user_id       TEXT PRIMARY KEY,  -- Nuvio auth.users.id, as profiles.nuvio_user_id
    tmdb_key_ciphertext BLOB NOT NULL,     -- nonce || AES-GCM sealed key
    tmdb_key_last4      TEXT NOT NULL,     -- the key's last four characters, shown to its owner
    updated_at          TEXT NOT NULL
);

CREATE INDEX folder_catalogs_by_catalog ON folder_catalogs (catalog_id);
